#!/usr/bin/tclsh
set V 0.026;
puts "Enter the following parameters: \n ";
puts "1. substrate doping and 10 to the power of \n";
set dop1 [gets stdin];
set bas [gets stdin];
set dop [expr $dop1*pow(10,$bas)];
puts "2. Intrinsic carrier concentration and 10 to the power of\n";
set int1 [gets stdin];
set bas1 [gets stdin];
set int [expr $int1*pow(10,$bas1)];
set fi1 [expr $int/$dop ];
set fi [expr $V*log($fi1)];
puts " 3. oxide thickness and 10 to the power of \n";
set t1 [gets stdin];
set bas2 [gets stdin];
set t [expr $t1*pow(10,$bas2)];
set cox [expr 3.97*8.854*pow(10,-14)/$t];
puts "4. Body coefficient\n";
set gamma [gets stdin];
puts "5. Oxide charge and 10 to the power of\n";
set charge1 [gets stdin];
set bas3 [gets stdin];
set charge2 [expr 1.6*pow(10,-19)*$charge1*pow(10,$bas3)];
puts "6. metal work function\n";
set metal [gets stdin];
set dipesh [expr 8.854*11.7*pow(10,-14)*abs(2*$fi)];
set q1 [expr -1*sqrt(2*1.6*pow(10,-19)*$dop*$dipesh)];
set q [expr $q1/$cox];
set charge [expr $charge2/$cox];
set vt0 [expr ($fi-$metal)-(2*$fi)-$q-$charge];
puts "Threshold voltage is $vt0";