$V=0.026;
print("Enter the following parameters: \n ");
print ("1. substrate doping and 10 to the power of \n");
chomp($dop=<>);chomp($base=<>);
$dop=$dop*(10**$base);
print("2. Intrinsic carrier concentration and 10 to the power of\n");
chomp($int=<>);chomp($base1=<>);
$int=$int*(10**$base1);
my $fi,"\n";
$fi=$int/$dop;
$fi=$V*log($fi);
print (" 3. oxide thickness and 10 to the power of \n");
chomp($t=<>);chomp($bas2=<>);
$t=$t*(10**$bas2);
my $cox;
$cox=3.97*8.854*(10**(-14))/$t;
print("4. Body coefficient\n");
chomp($gamma=<>);
print("5. Oxide charge and 10 to the power of\n");
chomp($charge=<>);chomp($bas3=<>);
$charge=1.6*(10**(-19))*$charge*(10**$bas3);
print("6. metal work function\n");
chomp($metal=<>);
my $q;
$q=-1*sqrt(2*1.6*(10**(-19))*$dop*8.854*11.7*(10**(-14))*abs(2*$fi));
$q=$q/$cox;
$charge=$charge/$cox;
my $vt0;
$vt0=($fi-$metal)-(2*$fi)-$q-$charge;
print("Threshold voltage is $vt0\n");